[package]
name = "time_logger_play"
version = "0.1.0"
authors = ["sathishvinayk"]
edition = "2018"
licence = "MIT"
description = "Time logger just a sample code"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"